"""
Emit a paste-into-Supabase SQL script that deletes every remote row whose
primary key is *not* in the local canonical data (silver CSVs + reference
YAML).

This is the companion to ``--reset-reference``: that flag aligns the small
reference tables when their IDs have drifted; this generator targets the
"remote has extra rows we never published" case that the pipeline can't
fix on its own (per the project's "never auto-delete operational data"
rule).

Use::

    # Print the script to stdout
    python -m app.pipeline.recover.cleanup_sql

    # Write it to a file
    python -m app.pipeline.recover.cleanup_sql > cleanup.sql

The generated SQL is wrapped in a transaction with a ``ROLLBACK;`` at the
end. After the operator inspects the row counts emitted by the ``DELETE``
statements they change the final line to ``COMMIT;`` (or just run the
``DELETE`` block again outside the transaction). This makes it impossible
to lose data to a typo or a misread row count.

Delete order is FK-safe: documents → meetings → locations → meeting_types
→ projects, so no statement orphans a child row.

The script is deterministic given the current contents of
``app/data/silver/`` and ``app/data/reference/``, so two operators
running it back-to-back produce byte-identical output.
"""
from __future__ import annotations

import csv
import sys
from pathlib import Path
from typing import Iterable

from app.pipeline import config, reference
from app.pipeline.publish.supabase import TABLE_SPEC

CHUNK = 200  # SQL parsers tolerate large IN lists, but keep them readable.


def _read_csv_ids(path: Path, pk: str) -> list:
    if not path.exists():
        return []
    with open(path, newline="", encoding="utf-8") as f:
        return [row[pk] for row in csv.DictReader(f) if row.get(pk)]


def _format_id_list(values: Iterable) -> str:
    """Format a list of ids as a comma-separated SQL literal block.

    Numeric ids stay bare; anything that doesn't look like an integer is
    quoted as a SQL string (handles UUID-style PKs if the schema ever
    changes).
    """
    parts: list[str] = []
    for v in values:
        s = str(v).strip()
        if not s:
            continue
        try:
            int(s)
            parts.append(s)
        except ValueError:
            esc = s.replace("'", "''")
            parts.append(f"'{esc}'")
    return ",".join(parts)


def _canonical_ids() -> dict[str, list]:
    """Collect canonical PKs for every managed table from local sources."""
    return {
        "projects":       [r["project_id"]    for r in reference.projects()],
        "meeting_types":  [r["type_id"]       for r in reference.meeting_types()],
        "locations":      [r["location_id"]   for r in reference.locations()],
        "meetings":       _read_csv_ids(config.SILVER_MEETINGS,  "meeting_id"),
        "documents":      _read_csv_ids(config.SILVER_DOCUMENTS, "document_id"),
    }


# Tables are deleted in *reverse* FK order so children go first.
DELETE_ORDER: tuple[str, ...] = (
    "documents", "meetings", "locations", "meeting_types", "projects",
)


def _emit_delete(table: str, ids: list) -> list[str]:
    """Emit a SELECT (preview) + DELETE pair for one table."""
    pk = TABLE_SPEC[table]["pk"]
    n = len(ids)
    if n == 0:
        return [
            f"-- {table}: no canonical ids found locally; SKIPPED to avoid",
            f"--   accidentally wiping the whole table.",
            "",
        ]
    id_list = _format_id_list(ids)
    return [
        f"-- {table}: keep {n} canonical row(s); delete every other remote row.",
        f"select count(*) as {table}_extras_to_delete",
        f"  from public.{table} where {pk} not in ({id_list});",
        "",
        f"delete from public.{table}",
        f" where {pk} not in ({id_list});",
        "",
    ]


def generate() -> str:
    """Return the full SQL script as a string."""
    ids = _canonical_ids()

    lines: list[str] = [
        "-- Estero / EagleGIS — remote cleanup script.",
        "-- Generated by app.pipeline.recover.cleanup_sql from the current",
        "-- silver CSVs and reference YAML. Regenerate any time the canonical",
        "-- data changes.",
        "--",
        "-- HOW TO USE",
        "--   1. Run this whole script in the Supabase SQL editor as-is.",
        "--   2. The transaction ends with ROLLBACK so nothing is committed",
        "--      on the first pass; you can read every `*_extras_to_delete`",
        "--      count and confirm it's what you expect.",
        "--   3. When you're satisfied, change the final ROLLBACK to COMMIT",
        "--      (or re-run the DELETE statements outside the transaction).",
        "--",
        "-- WHY THIS EXISTS",
        "--   The pipeline never deletes from Supabase automatically. This",
        "--   script is the one-time operator action for cleaning up rows",
        "--   that were seeded into the remote before the pipeline took over",
        "--   and that the YAML/CSVs don't claim.",
        "--",
        f"-- Canonical row counts (local): "
        + ", ".join(f"{t}={len(ids[t])}" for t in DELETE_ORDER[::-1]),
        "",
        "begin;",
        "",
    ]
    for table in DELETE_ORDER:
        lines.extend(_emit_delete(table, ids[table]))
    lines.extend([
        "-- Inspect the four `*_extras_to_delete` counts above before you",
        "-- promote this to COMMIT.",
        "rollback;",
        "",
    ])
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    sys.stdout.write(generate())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
