from __future__ import annotations

PROJECT_ALIASES: dict[str, list[str]] = {
    "BERT Rail Trail": [
        "bert", "rail trail", "bonita-estero regional trail", "sunterra", "suntrail",
    ],
    "Septic to Sewer": [
        "septic", "sewer", "utility extension", "uep", "estero bay village",
        "sunny grove", "cypress bend", "broadway avenue east",
    ],
    "Corkscrew Road": [
        "corkscrew road", "corkscrew rd", "puente lane", "traffic signal",
    ],
    "Comprehensive Plan": [
        "comprehensive plan", "comp plan", "land development code",
    ],
    "Budget / Capital Improvement": [
        "budget", "capital improvement", "cip", "millage",
    ],
    "Estero on the River": [
        "estero on the river", "river oaks", "river oaks preserve",
    ],
    "Sandy Lane Improvements": [
        "sandy lane", "sandy lake bike", "sandy lane bike", "sandy lane right of way",
    ],
    "Broadway Avenue Utility Extension": [
        "broadway avenue east", "broadway ave. east", "broadway east",
        "broadway avenue west", "broadway ave. west", "broadway west",
    ],
    "Williams Road Improvements": [
        "williams road", "williams rd",
    ],
    "Estero Parkway Improvements": [
        "estero parkway",
    ],
    "Ben Hill Griffin Parkway Improvements": [
        "ben hill griffin",
    ],
    "Comprehensive Plan / Land Development Code": [
        "comprehensive plan", "land development code", "official zoning map",
    ],
}


LOCATION_SEEDS: dict[str, dict[str, object]] = {
    "Estero Village Hall": {
        "location_type": "Meeting Venue",
        "address": "9401 Corkscrew Palms Circle, Estero, FL 33928",
        "latitude": 26.4285,
        "longitude": -81.8068,
        "aliases": ["council chambers", "village hall", "9401 corkscrew palms"],
    },
    "Legacy Church": {
        "location_type": "Meeting Venue",
        "address": "21115 Design Parc Lane, Estero, FL 33928",
        "latitude": None,
        "longitude": None,
        "aliases": ["legacy church", "design parc lane"],
    },
    "Estero Fire Rescue": {
        "location_type": "Meeting Venue",
        "address": "21500 Three Oaks Parkway, Estero, FL 33928",
        "latitude": None,
        "longitude": None,
        "aliases": ["estero fire rescue", "21500 three oaks parkway"],
    },
    "BERT Rail Trail Corridor": {
        "location_type": "Trail",
        "address": "Estero, FL",
        "latitude": 26.4339,
        "longitude": -81.8157,
        "aliases": ["bert", "rail trail", "bonita-estero regional trail"],
    },
    "Corkscrew Road Widening Corridor": {
        "location_type": "Road",
        "address": "Corkscrew Road, Estero, FL",
        "latitude": 26.4363,
        "longitude": -81.7701,
        "aliases": ["corkscrew road", "corkscrew rd"],
    },
    "Corkscrew Rd / Puente Lane": {
        "location_type": "Road",
        "address": "Corkscrew Road at Puente Lane, Estero, FL",
        "latitude": 26.4312,
        "longitude": -81.7847,
        "aliases": ["puente lane"],
    },
    "Estero Bay Village Septic Area": {
        "location_type": "Infrastructure",
        "address": "Estero Bay Village, Estero, FL",
        "latitude": 26.4408,
        "longitude": -81.8225,
        "aliases": ["estero bay village"],
    },
    "Sunny Grove Septic Area": {
        "location_type": "Infrastructure",
        "address": "Sunny Grove, Estero, FL",
        "latitude": 26.4376,
        "longitude": -81.8128,
        "aliases": ["sunny grove"],
    },
    "Cypress Bend Septic Area": {
        "location_type": "Infrastructure",
        "address": "Cypress Bend, Estero, FL",
        "latitude": 26.4469,
        "longitude": -81.8116,
        "aliases": ["cypress bend"],
    },
    "Broadway Avenue East UEP": {
        "location_type": "Infrastructure",
        "address": "Broadway Avenue East, Estero, FL",
        "latitude": 26.442,
        "longitude": -81.8054,
        "aliases": ["broadway avenue east", "broadway east"],
    },
    "Broadway Avenue West UEP": {
        "location_type": "Infrastructure",
        "address": "Broadway Avenue West, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["broadway avenue west", "broadway ave. west", "broadway west"],
    },
    "Sandy Lane": {
        "location_type": "Road",
        "address": "Sandy Lane, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["sandy lane", "sandy lake"],
    },
    "Williams Road": {
        "location_type": "Road",
        "address": "Williams Road, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["williams road", "williams rd"],
    },
    "Estero Parkway": {
        "location_type": "Road",
        "address": "Estero Parkway, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["estero parkway"],
    },
    "Ben Hill Griffin Parkway": {
        "location_type": "Road",
        "address": "Ben Hill Griffin Parkway, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["ben hill griffin", "ben hill griffin parkway"],
    },
    "Three Oaks Parkway": {
        "location_type": "Road",
        "address": "Three Oaks Parkway, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["three oaks parkway"],
    },
    "US 41 / Tamiami Trail": {
        "location_type": "Road",
        "address": "US 41, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["us 41", "u.s. 41", "tamiami trail"],
    },
    "Coconut Road": {
        "location_type": "Road",
        "address": "Coconut Road, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["coconut road"],
    },
    "Broadway Avenue": {
        "location_type": "Road",
        "address": "Broadway Avenue, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["broadway avenue"],
    },
    "River Ranch Road": {
        "location_type": "Road",
        "address": "River Ranch Road, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["river ranch road"],
    },
    "River Oaks Preserve": {
        "location_type": "Park",
        "address": "River Oaks Preserve, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["river oaks preserve", "river oaks"],
    },
    "Estero River": {
        "location_type": "General Area",
        "address": "Estero River, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["estero river"],
    },
    "Coconut Point": {
        "location_type": "Development",
        "address": "Coconut Point, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["coconut point", "coconut point mall"],
    },
    "Miromar Outlets": {
        "location_type": "Development",
        "address": "Miromar Outlets, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["miromar outlets"],
    },
    "Koreshan State Park": {
        "location_type": "Park",
        "address": "Koreshan State Park, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["koreshan state park", "koreshan"],
    },
    "Hertz Arena": {
        "location_type": "Development",
        "address": "Hertz Arena, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["hertz arena"],
    },
    "Bella Terra": {
        "location_type": "Neighborhood",
        "address": "Bella Terra, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["bella terra"],
    },
    "Stoneybrook": {
        "location_type": "Neighborhood",
        "address": "Stoneybrook, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["stoneybrook"],
    },
    "Pelican Sound": {
        "location_type": "Neighborhood",
        "address": "Pelican Sound, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["pelican sound"],
    },
    "The Brooks": {
        "location_type": "Neighborhood",
        "address": "The Brooks, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["the brooks"],
    },
    "Shadow Wood": {
        "location_type": "Neighborhood",
        "address": "Shadow Wood, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["shadow wood"],
    },
    "University Village": {
        "location_type": "Development",
        "address": "University Village, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["university village"],
    },
    "Genova": {
        "location_type": "Development",
        "address": "Genova, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["genova"],
    },
    "Tidewater": {
        "location_type": "Neighborhood",
        "address": "Tidewater, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["tidewater"],
    },
    "WildBlue": {
        "location_type": "Neighborhood",
        "address": "WildBlue, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["wildblue", "wild blue"],
    },
    "Summercrest": {
        "location_type": "Development",
        "address": "Summercrest, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["summercrest", "toll brothers development"],
    },
}


SITE_LOCATION_OVERRIDES: dict[str, dict[str, object]] = {
    # PZDB items below describe project sites by intersection, named parcel,
    # or site address. These overrides prevent broad road/community aliases
    # from producing multiple generic map points for one project.
    "DOS2018-E005": {
        "address": "The Colonnade / Estero Townhomes site, 9301 Corkscrew Road, Estero, FL",
        "latitude": 26.432264859989,
        "longitude": -81.801155452524,
        "confidence": 1.0,
    },
    "DCI2024-E003": {
        "address": "Estero Townhomes EPD site, 9301 Corkscrew Road, Estero, FL",
        "latitude": 26.432264859989,
        "longitude": -81.801155452524,
        "confidence": 1.0,
    },
    "DCI2022-E006": {
        "address": "9000 Williams Road, Estero, FL",
        "latitude": 26.420956750596,
        "longitude": -81.80311832661,
        "confidence": 1.0,
    },
    "DOS2021-E009": {
        "address": "9501 Spring Run Boulevard, Estero, FL",
        "latitude": 26.395734095199,
        "longitude": -81.797042452636,
        "confidence": 1.0,
    },
    "DCI2021-E002": {
        "address": "Miromar Outlets, Estero, FL",
        "latitude": 26.438084,
        "longitude": -81.772808,
        "confidence": 1.0,
    },
    "DCI2021-E004": {
        "address": "10081 Estero Town Commons Place, Estero, FL",
        "latitude": 26.430921743825,
        "longitude": -81.785430080157,
        "confidence": 1.0,
    },
    "CPA2022-E002": {
        "address": "8801 Corkscrew Road, Estero, FL",
        "latitude": 26.434598214195,
        "longitude": -81.807374237947,
        "confidence": 1.0,
    },
    "DOS2021-E008": {
        "address": "Corkscrew Pines project site, Estero, FL",
        "latitude": 26.4383,
        "longitude": -81.7603,
        "confidence": 1.0,
    },
    "DOS2022-E008": {
        "address": "Corkscrew Pines project site, Estero, FL",
        "latitude": 26.4383,
        "longitude": -81.7603,
        "confidence": 1.0,
    },
    "LDO2022-E051": {
        "address": "Commons Club at The Brooks, Estero, FL",
        "latitude": 26.3974648,
        "longitude": -81.7889557,
        "confidence": 1.0,
    },
    "DCI2022-E005": {
        "address": "Woodfield Estero project site, northwest corner of US 41 & Coconut Road, Estero, FL",
        "latitude": 26.4022,
        "longitude": -81.815,
        "confidence": 1.0,
    },
    "DCI2020-E001": {
        "address": "Coconut Pointe Residences at Brooks Town Center site, Estero, FL",
        "latitude": 26.39711,
        "longitude": -81.78531,
        "confidence": 1.0,
    },
    "ADD2023-E003": {
        "address": "Marketplace at Coconut Point, 22780 Via Villagio, Estero, FL",
        "latitude": 26.413657789311,
        "longitude": -81.811493859539,
        "confidence": 1.0,
    },
    "DOS2023-E005": {
        "address": "10041 Estero Town Commons Place, Estero, FL",
        "latitude": 26.4306485776,
        "longitude": -81.787676765485,
        "confidence": 1.0,
    },
    "DOS2023-E002": {
        "address": "8801 Corkscrew Road, Estero, FL",
        "latitude": 26.434598214195,
        "longitude": -81.807374237947,
        "confidence": 1.0,
    },
    "DOS2023-E010": {
        "address": "Coconut Pointe Residences at Brooks Town Center site, Estero, FL",
        "latitude": 26.39711,
        "longitude": -81.78531,
        "confidence": 1.0,
    },
    "DOS2023-E009": {
        "address": "Downtown Estero project site, east of US 41 and north of Broadway Avenue East, Estero, FL",
        "latitude": 26.4432,
        "longitude": -81.807,
        "confidence": 1.0,
    },
    "DOS2022-E006": {
        "address": "Downtown Estero project site, east of US 41 and north of Broadway Avenue East, Estero, FL",
        "latitude": 26.4432,
        "longitude": -81.807,
        "confidence": 1.0,
    },
    "DOS2022-E009": {
        "address": "Downtown Estero project site, east of US 41 and north of Broadway Avenue East, Estero, FL",
        "latitude": 26.4432,
        "longitude": -81.807,
        "confidence": 1.0,
    },
    "LDO2024-E008": {
        "address": "Coconut Road & Oakwilde Boulevard, Estero, FL",
        "latitude": 26.398580002784,
        "longitude": -81.798864007834,
        "confidence": 1.0,
    },
    "DCI2024-E001": {
        "address": "8111 Broadway Avenue East, Estero, FL",
        "latitude": 26.44244610632,
        "longitude": -81.809993666508,
        "confidence": 1.0,
    },
    "DOS2019-E004": {
        "address": "8111 Broadway Avenue East, Estero, FL",
        "latitude": 26.44244610632,
        "longitude": -81.809993666508,
        "confidence": 1.0,
    },
    "DCI2024-E008": {
        "address": "8790 Broadway Avenue East, Estero, FL",
        "latitude": 26.440585868638,
        "longitude": -81.806135895572,
        "confidence": 1.0,
    },
    "LDO2024-E037": {
        "address": "Three Oaks Parkway & Oakwilde Boulevard, Estero, FL",
        "latitude": 26.413073989755,
        "longitude": -81.785739540023,
        "confidence": 1.0,
    },
    "DOS2024-E002": {
        "address": "Woodfield Estero project site, northwest corner of US 41 & Coconut Road, Estero, FL",
        "latitude": 26.4022,
        "longitude": -81.815,
        "confidence": 1.0,
    },
    "DOS2024-E005": {
        "address": "Ben Hill Griffin Parkway & Everblades Parkway North, Estero, FL",
        "latitude": 26.443920189721,
        "longitude": -81.773684686876,
        "confidence": 1.0,
    },
    "DOS2024-E007": {
        "address": "9000 Williams Road, Estero, FL",
        "latitude": 26.420956750596,
        "longitude": -81.80311832661,
        "confidence": 1.0,
    },
    "DOS2024-E008": {
        "address": "Summercrest / Estero Townhomes site, 9301 Corkscrew Road, Estero, FL",
        "latitude": 26.432264859989,
        "longitude": -81.801155452524,
        "confidence": 1.0,
    },
    "DCI2024-E005": {
        "address": "Home2 Suites proposed hotel site, Coconut Point Mall, Estero, FL",
        "latitude": 26.403277778,
        "longitude": -81.808611111,
        "confidence": 1.0,
    },
    "DOS2022-E001": {
        "address": "22800 Via Villagio, Estero, FL",
        "latitude": 26.412588048918,
        "longitude": -81.811355977231,
        "confidence": 1.0,
    },
    "ADD2025-E005": {
        "address": "22800 Via Villagio, Estero, FL",
        "latitude": 26.412588048918,
        "longitude": -81.811355977231,
        "confidence": 1.0,
    },
    "LDO2025-E020": {
        "address": "Estero Parkway & Three Oaks Parkway, Estero, FL",
        "latitude": 26.449389004358,
        "longitude": -81.788946037082,
        "confidence": 1.0,
    },
    "DOS2025-E006": {
        "address": "8790 Broadway Avenue East, Estero, FL",
        "latitude": 26.440585868638,
        "longitude": -81.806135895572,
        "confidence": 1.0,
    },
}


SITE_TEXT_LOCATION_OVERRIDES: list[dict[str, object]] = [
    {
        "text": "Village Initiated Rezoning - 9000 Williams Road Property",
        "address": "9000 Williams Road, Estero, FL",
        "latitude": 26.420956750596,
        "longitude": -81.80311832661,
        "confidence": 1.0,
    },
    {
        "text": "South Regional Library",
        "address": "18251 Three Oaks Parkway, Estero, FL",
        "latitude": 26.433779738905564,
        "longitude": -81.78952626707927,
        "confidence": 1.0,
    },
    {
        "text": "DOS2022- E011",
        "address": "12840 Corkscrew Road, Estero, FL",
        "latitude": 26.449146368339,
        "longitude": -81.742899851451,
        "confidence": 1.0,
    },
    {
        "text": "Island High Rise",
        "address": "Williams Road & Baybridge Boulevard, Estero, FL",
        "latitude": 26.419972358933,
        "longitude": -81.832872657959,
        "confidence": 0.95,
    },
    {
        "text": "Estero Crossing Residential - Corsa",
        "address": "10500 Corkscrew Road, Estero, FL",
        "latitude": 26.430907704137,
        "longitude": -81.783054229702,
        "confidence": 1.0,
    },
    {
        "text": "Culver's Coconut Point",
        "address": "Culver's Coconut Point site, Estero, FL",
        "latitude": 26.43176443654626,
        "longitude": -81.78539888774463,
        "confidence": 1.0,
    },
]


CATEGORY_TERMS: dict[str, list[str]] = {
    "Administrative": ["approve agenda", "approved agenda", "remote participation", "excused", "minutes"],
    "Consent Agenda": ["consent agenda"],
    "Ordinance": ["ordinance", "first reading", "second reading"],
    "Resolution": ["resolution"],
    "Contract Approval": ["contract", "task authorization", "change order", "agreement"],
    "Budget": ["budget", "millage", "capital improvement"],
    "Public Hearing": ["public hearing", "hearing"],
    "Public Comment": ["public comment"],
    "Presentation": ["presentation", "overview"],
    "Discussion": ["discussion", "workshop", "consensus", "direction"],
}
