from __future__ import annotations

PROJECT_ALIASES: dict[str, list[str]] = {
    "BERT Rail Trail": [
        "bert", "rail trail", "bonita-estero regional trail", "sunterra", "suntrail",
    ],
    "Septic to Sewer": [
        "septic", "sewer", "utility extension", "uep", "estero bay village",
        "sunny grove", "cypress bend", "broadway avenue east",
    ],
    "Corkscrew Road": [
        "corkscrew road", "corkscrew rd", "puente lane", "traffic signal",
    ],
    "Comprehensive Plan": [
        "comprehensive plan", "comp plan", "land development code",
    ],
    "Budget / Capital Improvement": [
        "budget", "capital improvement", "cip", "millage",
    ],
    "Estero on the River": [
        "estero on the river", "river oaks", "river oaks preserve",
    ],
    "Sandy Lane Improvements": [
        "sandy lane", "sandy lake bike", "sandy lane bike", "sandy lane right of way",
    ],
    "Broadway Avenue Utility Extension": [
        "broadway avenue east", "broadway ave. east", "broadway east",
        "broadway avenue west", "broadway ave. west", "broadway west",
    ],
    "Williams Road Improvements": [
        "williams road", "williams rd",
    ],
    "Estero Parkway Improvements": [
        "estero parkway",
    ],
    "Ben Hill Griffin Parkway Improvements": [
        "ben hill griffin",
    ],
    "Comprehensive Plan / Land Development Code": [
        "comprehensive plan", "land development code", "official zoning map",
    ],
}


LOCATION_SEEDS: dict[str, dict[str, object]] = {
    "Estero Village Hall": {
        "location_type": "Meeting Venue",
        "address": "9401 Corkscrew Palms Circle, Estero, FL 33928",
        "latitude": 26.4285,
        "longitude": -81.8068,
        "aliases": ["council chambers", "village hall", "9401 corkscrew palms"],
    },
    "Legacy Church": {
        "location_type": "Meeting Venue",
        "address": "21115 Design Parc Lane, Estero, FL 33928",
        "latitude": None,
        "longitude": None,
        "aliases": ["legacy church", "design parc lane"],
    },
    "Estero Fire Rescue": {
        "location_type": "Meeting Venue",
        "address": "21500 Three Oaks Parkway, Estero, FL 33928",
        "latitude": None,
        "longitude": None,
        "aliases": ["estero fire rescue", "21500 three oaks parkway"],
    },
    "BERT Rail Trail Corridor": {
        "location_type": "Trail",
        "address": "Estero, FL",
        "latitude": 26.4339,
        "longitude": -81.8157,
        "aliases": ["bert", "rail trail", "bonita-estero regional trail"],
    },
    "Corkscrew Road Widening Corridor": {
        "location_type": "Road",
        "address": "Corkscrew Road, Estero, FL",
        "latitude": 26.4363,
        "longitude": -81.7701,
        "aliases": ["corkscrew road", "corkscrew rd"],
    },
    "Corkscrew Rd / Puente Lane": {
        "location_type": "Road",
        "address": "Corkscrew Road at Puente Lane, Estero, FL",
        "latitude": 26.4312,
        "longitude": -81.7847,
        "aliases": ["puente lane"],
    },
    "Estero Bay Village Septic Area": {
        "location_type": "Infrastructure",
        "address": "Estero Bay Village, Estero, FL",
        "latitude": 26.4408,
        "longitude": -81.8225,
        "aliases": ["estero bay village"],
    },
    "Sunny Grove Septic Area": {
        "location_type": "Infrastructure",
        "address": "Sunny Grove, Estero, FL",
        "latitude": 26.4376,
        "longitude": -81.8128,
        "aliases": ["sunny grove"],
    },
    "Cypress Bend Septic Area": {
        "location_type": "Infrastructure",
        "address": "Cypress Bend, Estero, FL",
        "latitude": 26.4469,
        "longitude": -81.8116,
        "aliases": ["cypress bend"],
    },
    "Broadway Avenue East UEP": {
        "location_type": "Infrastructure",
        "address": "Broadway Avenue East, Estero, FL",
        "latitude": 26.442,
        "longitude": -81.8054,
        "aliases": ["broadway avenue east", "broadway east"],
    },
    "Broadway Avenue West UEP": {
        "location_type": "Infrastructure",
        "address": "Broadway Avenue West, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["broadway avenue west", "broadway ave. west", "broadway west"],
    },
    "Sandy Lane": {
        "location_type": "Road",
        "address": "Sandy Lane, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["sandy lane", "sandy lake"],
    },
    "Williams Road": {
        "location_type": "Road",
        "address": "Williams Road, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["williams road", "williams rd"],
    },
    "Estero Parkway": {
        "location_type": "Road",
        "address": "Estero Parkway, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["estero parkway"],
    },
    "Ben Hill Griffin Parkway": {
        "location_type": "Road",
        "address": "Ben Hill Griffin Parkway, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["ben hill griffin", "ben hill griffin parkway"],
    },
    "Three Oaks Parkway": {
        "location_type": "Road",
        "address": "Three Oaks Parkway, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["three oaks parkway"],
    },
    "US 41 / Tamiami Trail": {
        "location_type": "Road",
        "address": "US 41, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["us 41", "u.s. 41", "tamiami trail"],
    },
    "Coconut Road": {
        "location_type": "Road",
        "address": "Coconut Road, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["coconut road"],
    },
    "Broadway Avenue": {
        "location_type": "Road",
        "address": "Broadway Avenue, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["broadway avenue"],
    },
    "River Ranch Road": {
        "location_type": "Road",
        "address": "River Ranch Road, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["river ranch road"],
    },
    "River Oaks Preserve": {
        "location_type": "Park",
        "address": "River Oaks Preserve, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["river oaks preserve", "river oaks"],
    },
    "Estero River": {
        "location_type": "General Area",
        "address": "Estero River, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["estero river"],
    },
    "Coconut Point": {
        "location_type": "Development",
        "address": "Coconut Point, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["coconut point", "coconut point mall"],
    },
    "Miromar Outlets": {
        "location_type": "Development",
        "address": "Miromar Outlets, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["miromar outlets"],
    },
    "Koreshan State Park": {
        "location_type": "Park",
        "address": "Koreshan State Park, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["koreshan state park", "koreshan"],
    },
    "Hertz Arena": {
        "location_type": "Development",
        "address": "Hertz Arena, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["hertz arena"],
    },
    "Bella Terra": {
        "location_type": "Neighborhood",
        "address": "Bella Terra, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["bella terra"],
    },
    "Stoneybrook": {
        "location_type": "Neighborhood",
        "address": "Stoneybrook, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["stoneybrook"],
    },
    "Pelican Sound": {
        "location_type": "Neighborhood",
        "address": "Pelican Sound, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["pelican sound"],
    },
    "The Brooks": {
        "location_type": "Neighborhood",
        "address": "The Brooks, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["the brooks"],
    },
    "Shadow Wood": {
        "location_type": "Neighborhood",
        "address": "Shadow Wood, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["shadow wood"],
    },
    "University Village": {
        "location_type": "Development",
        "address": "University Village, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["university village"],
    },
    "Genova": {
        "location_type": "Development",
        "address": "Genova, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["genova"],
    },
    "Tidewater": {
        "location_type": "Neighborhood",
        "address": "Tidewater, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["tidewater"],
    },
    "WildBlue": {
        "location_type": "Neighborhood",
        "address": "WildBlue, Estero, FL",
        "latitude": None,
        "longitude": None,
        "aliases": ["wildblue", "wild blue"],
    },
}


CATEGORY_TERMS: dict[str, list[str]] = {
    "Administrative": ["approve agenda", "approved agenda", "remote participation", "excused", "minutes"],
    "Consent Agenda": ["consent agenda"],
    "Ordinance": ["ordinance", "first reading", "second reading"],
    "Resolution": ["resolution"],
    "Contract Approval": ["contract", "task authorization", "change order", "agreement"],
    "Budget": ["budget", "millage", "capital improvement"],
    "Public Hearing": ["public hearing", "hearing"],
    "Public Comment": ["public comment"],
    "Presentation": ["presentation", "overview"],
    "Discussion": ["discussion", "workshop", "consensus", "direction"],
}
