-- EagleGIS normalized PostgreSQL schema
-- Designed for Supabase/PostgreSQL.

CREATE TABLE public.meeting_types (
  type_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_name varchar(120) NOT NULL UNIQUE,
  description text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.locations (
  location_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_name varchar(255) NOT NULL,
  location_type varchar(80)
    CHECK (location_type IN (
      'Meeting Venue',
      'Trail',
      'Road',
      'Infrastructure',
      'Park',
      'Development',
      'Neighborhood',
      'Parcel',
      'General Area'
    )),
  address text,
  description text,
  latitude numeric(9,6)
    CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
  longitude numeric(9,6)
    CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.meetings (
  meeting_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_id integer NOT NULL
    REFERENCES public.meeting_types(type_id),
  meeting_date date,
  meeting_year integer
    CHECK (meeting_year IS NULL OR meeting_year BETWEEN 2015 AND 2030),
  venue_location_id integer
    REFERENCES public.locations(location_id),
  venue_name varchar(255),
  venue_address text,
  start_time varchar(40),
  end_time varchar(40),
  status varchar(40) NOT NULL DEFAULT 'Pending'
    CHECK (status IN ('Accepted', 'Pending', 'Rejected', 'Tabled', 'Cancelled')),
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.documents (
  document_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id integer NOT NULL
    REFERENCES public.meetings(meeting_id) ON DELETE CASCADE,
  title varchar(255) NOT NULL,
  document_type varchar(80)
    CHECK (document_type IN (
      'Agenda',
      'Staff Report',
      'Resolution',
      'Ordinance',
      'Minutes',
      'Presentation',
      'Public Notice',
      'Packet'
    )),
  file_name varchar(255),
  file_url text,
  upload_date date,
  doc_date date,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.projects (
  project_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_name varchar(255) NOT NULL UNIQUE,
  description text,
  start_year integer
    CHECK (start_year IS NULL OR start_year BETWEEN 2015 AND 2030),
  status varchar(40) NOT NULL DEFAULT 'Active'
    CHECK (status IN ('Active', 'Completed', 'Pending', 'On Hold')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.agenda_categories (
  category_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_name varchar(120) NOT NULL UNIQUE,
  description text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.agenda_items (
  item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id integer NOT NULL
    REFERENCES public.meetings(meeting_id) ON DELETE CASCADE,
  category_id integer
    REFERENCES public.agenda_categories(category_id),
  item_order integer,
  item_title varchar(500),
  item_text text NOT NULL,
  action_taken text,
  action_type varchar(80)
    CHECK (action_type IN (
      'Vote',
      'Motion',
      'Discussion',
      'Presentation',
      'Public Comment',
      'Public Hearing',
      'Consent Agenda',
      'Ordinance',
      'Resolution',
      'Contract Approval',
      'Budget',
      'Administrative',
      'No Action',
      'Unknown'
    )),
  vote_detected boolean NOT NULL DEFAULT false,
  vote_result varchar(120),
  motion_text text,
  staff_code varchar(80),
  needs_review boolean NOT NULL DEFAULT false,
  extraction_confidence numeric(4,3)
    CHECK (extraction_confidence IS NULL OR extraction_confidence BETWEEN 0 AND 1),
  extraction_notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (meeting_id, item_order)
);

CREATE TABLE public.agenda_item_projects (
  item_id integer NOT NULL
    REFERENCES public.agenda_items(item_id) ON DELETE CASCADE,
  project_id integer NOT NULL
    REFERENCES public.projects(project_id) ON DELETE CASCADE,
  PRIMARY KEY (item_id, project_id)
);

CREATE TABLE public.agenda_item_locations (
  item_id integer NOT NULL
    REFERENCES public.agenda_items(item_id) ON DELETE CASCADE,
  location_id integer NOT NULL
    REFERENCES public.locations(location_id) ON DELETE CASCADE,
  PRIMARY KEY (item_id, location_id)
);

CREATE INDEX idx_meetings_type_id
  ON public.meetings(type_id);

CREATE INDEX idx_meetings_meeting_date
  ON public.meetings(meeting_date);

CREATE INDEX idx_meetings_venue_location_id
  ON public.meetings(venue_location_id);

CREATE INDEX idx_documents_meeting_id
  ON public.documents(meeting_id);

CREATE INDEX idx_documents_document_type
  ON public.documents(document_type);

CREATE INDEX idx_agenda_items_meeting_id
  ON public.agenda_items(meeting_id);

CREATE INDEX idx_agenda_items_category_id
  ON public.agenda_items(category_id);

CREATE INDEX idx_agenda_items_action_type
  ON public.agenda_items(action_type);

CREATE INDEX idx_agenda_items_needs_review
  ON public.agenda_items(needs_review);

CREATE INDEX idx_agenda_item_projects_project_id
  ON public.agenda_item_projects(project_id);

CREATE INDEX idx_agenda_item_locations_location_id
  ON public.agenda_item_locations(location_id);

CREATE INDEX idx_locations_coordinates
  ON public.locations(latitude, longitude);

CREATE INDEX idx_projects_status
  ON public.projects(status);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_meeting_types_updated_at
BEFORE UPDATE ON public.meeting_types
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_locations_updated_at
BEFORE UPDATE ON public.locations
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_meetings_updated_at
BEFORE UPDATE ON public.meetings
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_documents_updated_at
BEFORE UPDATE ON public.documents
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_projects_updated_at
BEFORE UPDATE ON public.projects
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_agenda_categories_updated_at
BEFORE UPDATE ON public.agenda_categories
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_agenda_items_updated_at
BEFORE UPDATE ON public.agenda_items
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
